services:
  postgres:
    image: postgres:16
    container_name: optuna
    restart: always
    environment:
      POSTGRES_USER: optuna
      POSTGRES_PASSWORD: assword
      POSTGRES_DB: optuna_db
    ports:
      - "5445:5432"
    volumes:
      - ./data_to_save:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U optuna -d optuna_db"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - optuna_network

networks:
  optuna_network:
    driver: bridge